-- Insert comprehensive fly collection
INSERT INTO flies (name, type, size, color, description, best_conditions) VALUES

-- DRY FLIES (15 flies)
('Adams', 'dry', '16', 'Gray', 'Classic dry fly pattern, excellent for mayfly hatches', '{"weather": ["sunny", "cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "afternoon", "dusk"], "water_temperature_range": {"min": 45, "max": 70}}'),
('Elk Hair Caddis', 'dry', '14', 'Brown', 'Versatile dry fly for caddis hatches', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "afternoon", "dusk"], "water_temperature_range": {"min": 50, "max": 75}}'),
('Parachute Adams', 'dry', '20', 'Gray', 'High-visibility dry fly for difficult conditions', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 45, "max": 70}}'),
('Royal Wulff', 'dry', '12', 'Multi', 'High-floating dry fly for rough water', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 50, "max": 75}}'),
('Blue Winged Olive', 'dry', '18', 'Olive', 'Essential mayfly pattern for spring and fall', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "afternoon", "dusk"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Light Cahill', 'dry', '14', 'Yellow', 'Classic mayfly imitation for summer evenings', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["afternoon", "dusk"], "water_temperature_range": {"min": 50, "max": 75}}'),
('Pale Morning Dun', 'dry', '16', 'Yellow', 'Spring and early summer mayfly pattern', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear"], "water_level": ["normal", "low"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 45, "max": 70}}'),
('Quill Gordon', 'dry', '14', 'Gray', 'Early spring mayfly, excellent for cold water', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 35, "max": 60}}'),
('March Brown', 'dry', '12', 'Brown', 'Large mayfly for spring fishing', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Hendrickson', 'dry', '14', 'Brown', 'Spring mayfly pattern, highly effective', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["afternoon", "dusk"], "water_temperature_range": {"min": 45, "max": 70}}'),
('Griffiths Gnat', 'dry', '20', 'Black', 'Tiny midge pattern for selective fish', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear"], "water_level": ["normal", "low"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 35, "max": 60}}'),
('Stimulator', 'dry', '10', 'Yellow', 'Attractor pattern that floats well', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 45, "max": 75}}'),
('Chernobyl Ant', 'dry', '8', 'Black', 'Large terrestrial pattern for summer', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["summer", "late_summer", "early_fall"], "water_temperature_range": {"min": 50, "max": 80}}'),
('Hopper', 'dry', '8', 'Green', 'Grasshopper imitation for late summer', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 55, "max": 80}}'),
('Spinner', 'dry', '16', 'Gray', 'Spent mayfly pattern for evening fishing', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["dusk", "night"], "water_temperature_range": {"min": 45, "max": 70}}'),

-- NYMPHS (15 flies)
('Pheasant Tail Nymph', 'nymph', '18', 'Brown', 'Effective nymph pattern for subsurface fishing', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["clear", "slightly_murky", "murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Hare''s Ear Nymph', 'nymph', '16', 'Brown', 'Natural-looking nymph pattern', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Zebra Midge', 'nymph', '22', 'Black', 'Small midge pattern for selective fish', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear"], "water_level": ["normal", "low"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 35, "max": 60}}'),
('Prince Nymph', 'nymph', '14', 'Black', 'Versatile nymph with good visibility', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["clear", "slightly_murky", "murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 70}}'),
('Copper John', 'nymph', '16', 'Copper', 'Heavy nymph that sinks quickly', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky", "very_murky"], "water_level": ["normal", "high", "flooding"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 35, "max": 70}}'),
('San Juan Worm', 'nymph', '12', 'Red', 'Simple but effective worm imitation', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky", "very_murky"], "water_level": ["normal", "high", "flooding"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 35, "max": 70}}'),
('Pheasant Tail Soft Hackle', 'nymph', '16', 'Brown', 'Soft hackle version of pheasant tail', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Bead Head Pheasant Tail', 'nymph', '18', 'Brown', 'Weighted version for deeper water', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["clear", "slightly_murky", "murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Zug Bug', 'nymph', '12', 'Black', 'Heavy stonefly nymph imitation', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky"], "water_level": ["normal", "high", "flooding"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 35, "max": 65}}'),
('Gold Ribbed Hare''s Ear', 'nymph', '14', 'Brown', 'Classic nymph with gold ribbing', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Disco Midge', 'nymph', '20', 'Black', 'Flashy midge pattern', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 35, "max": 60}}'),
('Barr''s Emerger', 'nymph', '18', 'Gray', 'Emerging mayfly pattern', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "afternoon", "dusk"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Serendipity', 'nymph', '18', 'Brown', 'Effective midge pattern', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 35, "max": 60}}'),
('RS2', 'nymph', '20', 'Gray', 'Small mayfly emerger pattern', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear"], "water_level": ["normal", "low"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 35, "max": 60}}'),
('Bead Head Prince', 'nymph', '14', 'Black', 'Weighted prince nymph', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["clear", "slightly_murky", "murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 70}}'),

-- STREAMERS (10 flies)
('Woolly Bugger', 'streamer', '8', 'Black', 'Versatile streamer that imitates various aquatic creatures', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky", "very_murky"], "water_level": ["normal", "high", "flooding"], "time_of_day": ["dawn", "morning", "dusk", "night"], "water_temperature_range": {"min": 35, "max": 70}}'),
('Muddler Minnow', 'streamer', '6', 'Brown', 'Classic streamer for trout and bass', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky"], "water_level": ["normal", "high"], "time_of_day": ["dawn", "morning", "dusk"], "water_temperature_range": {"min": 40, "max": 70}}'),
('Clouser Minnow', 'streamer', '4', 'White', 'Excellent baitfish imitation', '{"weather": ["sunny", "cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky", "murky"], "water_level": ["normal", "high"], "time_of_day": ["dawn", "morning", "afternoon", "dusk"], "water_temperature_range": {"min": 45, "max": 75}}'),
('Zonker', 'streamer', '6', 'White', 'Rabbit fur streamer with great action', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky"], "water_level": ["normal", "high"], "time_of_day": ["dawn", "morning", "dusk"], "water_temperature_range": {"min": 40, "max": 70}}'),
('Sculpin', 'streamer', '4', 'Brown', 'Bottom-dwelling fish imitation', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky", "very_murky"], "water_level": ["normal", "high"], "time_of_day": ["dawn", "morning", "dusk"], "water_temperature_range": {"min": 35, "max": 65}}'),
('Lefty''s Deceiver', 'streamer', '2', 'White', 'Saltwater pattern that works in fresh water', '{"weather": ["sunny", "cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["dawn", "morning", "afternoon", "dusk"], "water_temperature_range": {"min": 45, "max": 75}}'),
('Bunny Leech', 'streamer', '6', 'Black', 'Rabbit fur leech imitation', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky"], "water_level": ["normal", "high"], "time_of_day": ["dawn", "morning", "dusk", "night"], "water_temperature_range": {"min": 35, "max": 70}}'),
('Marabou Muddler', 'streamer', '8', 'Brown', 'Marabou streamer with muddler head', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky"], "water_level": ["normal", "high"], "time_of_day": ["dawn", "morning", "dusk"], "water_temperature_range": {"min": 40, "max": 70}}'),
('Sculpin Helgramite', 'streamer', '6', 'Brown', 'Large stonefly nymph imitation', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky"], "water_level": ["normal", "high", "flooding"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 35, "max": 65}}'),
('Sex Dungeon', 'streamer', '4', 'Black', 'Modern articulated streamer', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["slightly_murky", "murky"], "water_level": ["normal", "high"], "time_of_day": ["dawn", "morning", "dusk"], "water_temperature_range": {"min": 40, "max": 70}}'),

-- WET FLIES (5 flies)
('Soft Hackle Pheasant Tail', 'wet', '16', 'Brown', 'Traditional wet fly pattern', '{"weather": ["cloudy", "overcast", "rainy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Partridge and Orange', 'wet', '14', 'Orange', 'Classic wet fly for trout', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Soft Hackle Hare''s Ear', 'wet', '16', 'Brown', 'Wet fly version of hare''s ear', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Sawyer''s Killer Bug', 'wet', '12', 'Brown', 'Effective wet fly for grayling and trout', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),
('Spider', 'wet', '14', 'Brown', 'Traditional spider pattern', '{"weather": ["cloudy", "overcast"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "high"], "time_of_day": ["morning", "midday", "afternoon"], "water_temperature_range": {"min": 40, "max": 65}}'),

-- TERRESTRIALS (5 flies)
('Ant', 'terrestrial', '16', 'Black', 'Classic ant imitation for summer', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 50, "max": 80}}'),
('Beetle', 'terrestrial', '14', 'Black', 'Beetle imitation for summer fishing', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 50, "max": 80}}'),
('Cricket', 'terrestrial', '12', 'Brown', 'Cricket pattern for late summer', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 55, "max": 80}}'),
('Flying Ant', 'terrestrial', '18', 'Black', 'Flying ant for summer hatches', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["afternoon", "dusk"], "water_temperature_range": {"min": 50, "max": 80}}'),
('Cicada', 'terrestrial', '6', 'Black', 'Large cicada imitation', '{"weather": ["sunny", "cloudy"], "water_clarity": ["clear", "slightly_murky"], "water_level": ["normal", "low"], "time_of_day": ["morning", "afternoon"], "water_temperature_range": {"min": 60, "max": 85}}');

-- Verify the insert
SELECT COUNT(*) as total_flies FROM flies;
SELECT type, COUNT(*) as count FROM flies GROUP BY type ORDER BY type;
